[package]
name = "plonk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.3"
ark-ff = "0.3"
ark-std = "0.3"
ark-relations = "0.3"
ark-crypto-primitives = "0.3"
ark-groth16 = "0.3"
ark-poly = "0.3" 
ark-poly-commit = "0.3"