pub mod ast;
pub mod lexer;
pub mod type_checker;
pub mod evaluator;

use lalrpop_util::lalrpop_mod;

// This will be generated by LALRPOP
#[allow(clippy::all)]
lalrpop_mod!(pub parser, "/language_frontend/parser.rs");


pub use ast::{Expr, Type, Value};
pub use evaluator::eval;
pub use type_checker::type_check; 